service: aws-lambda-benchmark
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  environment:
    S3_BUCKET: ${self:service}-bucket-fmasz8
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*'

functions:
  test128:
    handler: handler.tester
    memorySize: 128
    timeout: 30
    events:
      - httpApi:
          path: /test128
          method: get
  test512:
    handler: handler.tester
    memorySize: 512
    timeout: 30
    events:
      - httpApi:
          path: /test512
          method: get
  test1024:
    handler: handler.tester
    memorySize: 1024
    timeout: 30
    events:
      - httpApi:
          path: /test1024
          method: get
  test1536:
    handler: handler.tester
    memorySize: 1536
    timeout: 30
    events:
      - httpApi:
          path: /test1536
          method: get
  test2048:
    handler: handler.tester
    memorySize: 2048
    timeout: 30
    events:
      - httpApi:
          path: /test2048
          method: get
  test3072:
    handler: handler.tester
    memorySize: 3072
    timeout: 30
    events:
      - httpApi:
          path: /test3072
          method: get
  test4096:
    handler: handler.tester
    memorySize: 4096
    timeout: 30
    events:
      - httpApi:
          path: /test4096
          method: get
  test5120:
    handler: handler.tester
    memorySize: 5120
    timeout: 30
    events:
      - httpApi:
          path: /test5120
          method: get
  test6144:
    handler: handler.tester
    memorySize: 6144
    timeout: 30
    events:
      - httpApi:
          path: /test6144
          method: get
  test7168:
    handler: handler.tester
    memorySize: 7168
    timeout: 30
    events:
      - httpApi:
          path: /test7168
          method: get
  test8192:
    handler: handler.tester
    memorySize: 8192
    timeout: 30
    events:
      - httpApi:
          path: /test8192
          method: get
  test9216:
    handler: handler.tester
    memorySize: 9216
    timeout: 30
    events:
      - httpApi:
          path: /test9216
          method: get
  test10240:
    handler: handler.tester
    memorySize: 10240
    timeout: 30
    events:
      - httpApi:
          path: /test10240
          method: get
  info128:
    handler: handler.info
    memorySize: 128
    events:
      - httpApi:
          path: /info128
          method: get
  info512:
    handler: handler.info
    memorySize: 512
    events:
      - httpApi:
          path: /info512
          method: get
  info1024:
    handler: handler.info
    memorySize: 1024
    events:
      - httpApi:
          path: /info1024
          method: get
  info1536:
    handler: handler.info
    memorySize: 1536
    events:
      - httpApi:
          path: /info1536
          method: get
  info2048:
    handler: handler.info
    memorySize: 2048
    events:
      - httpApi:
          path: /info2048
          method: get
  info3072:
    handler: handler.info
    memorySize: 3072
    events:
      - httpApi:
          path: /info3072
          method: get
  info4096:
    handler: handler.info
    memorySize: 4096
    events:
      - httpApi:
          path: /info4096
          method: get
  info5120:
    handler: handler.info
    memorySize: 5120
    events:
      - httpApi:
          path: /info5120
          method: get
  info6144:
    handler: handler.info
    memorySize: 6144
    events:
      - httpApi:
          path: /info6144
          method: get
  info7168:
    handler: handler.info
    memorySize: 7168
    events:
      - httpApi:
          path: /info7168
          method: get
  info8192:
    handler: handler.info
    memorySize: 8192
    events:
      - httpApi:
          path: /info8192
          method: get
  info9216:
    handler: handler.info
    memorySize: 9216
    events:
      - httpApi:
          path: /info9216
          method: get
  info10240:
    handler: handler.info
    memorySize: 10240
    events:
      - httpApi:
          path: /info10240
          method: get


resources:
  Resources:
    S3TranscriptionBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}